### ISSUE TITLE
Replay not working

### ISSUE THREAD

**Issue by lukas-gitl** [davepeck/httreplay#9]
Below is a minimal example that will still access the server when replayed. However the buffered data is returned. I suspect it has to do with https. Using requests 2.4.3 and httreplay 0.1.6.

    import os
    import unittest
    import httreplay
    import requests
    
    
    class AbstractBaseTest(unittest.TestCase):
    
        def setUp(self):
            """Start replay recording."""
            httreplay.start_replay(
                replay_file_name=os.path.join(
                    os.path.abspath(os.path.dirname(__file__)),
                    "tmp.json"
                )
            )
    
        def tearDown(self):
            """Stop replay recording."""
            httreplay.stop_replay()
    
        def test_call(self):
            result = requests.get(
                "https://www.random.org/strings/"
                "?num=10&len=8&digits=on&upperalpha=on&loweralpha=on"
                "&unique=on&format=plain&rnd=new"
            )
            print result.text

**Comment by davepeck** [comment]
Looks like things are working now. Closing!

**Comment by lukas-gitl** [comment]
Nop, this is still now working... when I turn off my internet it throws an error.

**Comment by davepeck** [comment]
Please include a full stack trace. Thanks.

**Comment by lukas-gitl** [comment]
Using httreplay==0.1.7 and requests==2.5.1 now. Cheers!
>>> Error
Traceback (most recent call last):
  File "tests/tmp.py", line 24, in test_call
    "https://www.random.org/strings/"
  File "env/local/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "env/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "env/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "env/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "env/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by davepeck** [comment]
Oh, I see. This is interesting in the sense that we're still doing a `getaddrinfo()` call deep inside the `requests` networking stack and, because you've turned off your network it's blowing up. The thing is: if we got _past_ this call, we'd end up getting into `httreplay` code. I'm not sure there's an easy fix here, nor am I convinced it's really important to fix -- fully disconnecting your network to "test" `httreplay` seems like a nice idea, but I guess it has unintended side-effects.

I'll think about this -- I may find a fix, or I may decide it's a WONTFIX.

**Comment by lukas-gitl** [comment]
Thanks for the feedback! The problem is that the endpoint is still being hit (if I leave the network on). So if it is slow to respond (in my case sometimes it's four seconds), the tests will run a very long time :-)

**Comment by davepeck** [comment]
Hrm...

**Comment by lukas-gitl** [comment]
Haha, don't worry too much about it. However it would be really nice to get this fixed. What's the tricky part about patching it?

**Comment by davepeck** [comment]
I need to spend a little time on this to understand it better, but it looks like we might need to patch at a different point? Not sure -- requires further investigation.
